# Generated by Django 3.2.8 on 2021-10-24 15:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciesClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ThePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateTimeField()),
                ('rooms', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('roomOrFlat', models.BooleanField(default=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('owner', models.CharField(max_length=50)),
                ('isAgent', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.theplace')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/<function image_directory_field at 0x7f14e99bc670>')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.record')),
            ],
        ),
    ]
