# Generated by Django 3.2.8 on 2021-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='images/<function image_directory_field at 0x7fdd99e2a670>'),
        ),
    ]
