# Generated by Django 3.2.8 on 2021-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_alter_photos_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='images/<function image_directory_field at 0x7f90220e4670>'),
        ),
    ]
