# Generated by Django 3.2.8 on 2021-10-24 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_alter_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rooms',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
